= [.tech]#OOPS# projections and automatic table substitution

// Здесь хорошо бы дать расшифровку аббревиатуры OOPS в скобках
The [.tech]#OOPS# provides some functions simplifying creation and usage of projections.
In future it may be added to SQL grammar, so that it is possible to write:

// Здесь, возможно, нужно побить это выражение на несколько строк
[source,sql]
----
CREATE PROJECTION xxx OF TABLE yyy(column1, column2,...) GROUP BY (column1, column2, ...)
----

But right now it can be done using function:

:object_name: create_projection
:object_type: Function
include::partials/_docstring_open.adoc[]

[source,postgres]
----
create_projection(
    projection_name text,
    source_table regclass,
    vector_columns text[],
    scalar_columns text[] default null,
    order_by text default null)
----

:attribute_name: projection_name
:attribute_value: text
:attribute_is_optional:
:attribute_description: Name of the projection (`PNAME` below)
include::partials/_attribute_definition.adoc[]

:attribute_name: source_table
:attribute_value: regclass
:attribute_is_optional:
:attribute_description: Existing [.tech]#Postgres# table to be substituted by projection
include::partials/_attribute_definition.adoc[]

:attribute_name: vector_columns
:attribute_value: text[]
:attribute_is_optional:
:attribute_description: Array of column names which should be stores as [.tech]#OOPS# tiles
include::partials/_attribute_definition.adoc[]

:attribute_name: scalar_columns
:attribute_value: text[]
:attribute_is_optional:
:attribute_description: Array of grouping columns which type is preserved
include::partials/_attribute_definition.adoc[]
// Судя по наличию default параметр scalar_columns тоже опциональный? Тогда нужно будет добавить здесь optional

:attribute_name: order_by
:attribute_value: text
:attribute_is_optional: optional
:attribute_description: Name of ordering attribute
include::partials/_attribute_definition.adoc[]

The `+create_projection(PNAME,...)+` function does the following:

[arabic]
. Creates projection table with specified name and attributes.
. Creates `+PNAME_refresh()+` functions which can be used to update projection. 
// Здесь и далее нужна будет ссылка на описание (докстринг) PNAME_refresh()
. Inserts information about created projection in `+OOPS_projections+` table.
// Здесь нужна будет ссылка на описание (докстринг) OOPS_projections

This table is used by optimizer to automatically substitute table with projection.

include::partials/_docstring_close.adoc[]

The `<<order_by>>` attribute is one of the OOPS projection vector columns by which data is sorted. 
Presence of such column in projection allows to incrementally update projection.
Generated `+PNAME_refresh()+` method calls `+populate()+` method, selecting from original table only rows with `<<order_by>>` column value greater than maximal value of this column
in projection.
It assumes that `<<order_by>>` is unique or at least refresh is done at the moment when there is some gap in collected events.

Like materialized views, [.tech]#OOPS# projections are not updated automatically.
It is responsibility of a programmer to periodically refresh them.
The most convenient way is to use generated `+PNAME_refresh()+` function.
If `<<order_by>>` attribute is specified, this function imports from original table only the new data (not present in projection).

The main advantage of [.tech]#OOPS# projection mechanism is that it allows to automatically substitute queries on original tables with projections.
There is `+OOPS.auto_substitute_projections+` configuration parameter which allows to switch on such substitution.
// Здесь нужна будет ссылка на описание параметра OOPS.auto_substitute_projections
By default it is switched off, because OOPS projects may be not synchronized with original table and query on projection may return different result.

Right now projections can be automatically substituted only if:

[arabic]
. Query doesn’t contain JOINs.
. Query performs aggregation of vector (tile) columns.
. All other expressions in target list, `+ORDER BY+` / `+GROUP BY+`
clauses refer only to scalar attributes of projection.

Example of using projections:

// В этом примере хорошо бы было показать результаты выполнения запросов
// Насколько я понимаю, должна быть какая-то разница во времени выполнения с OOPS и без
// В таком виде, как сейчас, пример не очень показателен
[source,postgres]
----
create extension OOPS;

-- Let's create a demo table
create table lineitem(
    l_orderkey integer,
    l_partkey integer,
    l_suppkey integer,
    l_linenumber integer,
    l_quantity real,
    l_extendedprice real,
    l_discount real,
    l_tax real,
    l_returnflag "char",
    l_linestatus "char",
    l_shipdate date,
    l_commitdate date,
    l_receiptdate date,
    l_shipinstruct char(25),
    l_shipmode char(10),
    l_comment char(44),
    l_dummy char(1));

select
create_projection(
    'OOPS_lineitem',
    'lineitem',
    array['l_shipdate','l_quantity','l_extendedprice','l_discount','l_tax'],
    array['l_returnflag','l_linestatus']);

-- Switching on timing to see the difference
\timing

-- Copying demo table
copy lineitem from '/mnt/data/lineitem.tbl' delimiter '|' csv;

-- Refreshing the projections
select OOPS_lineitem_refresh();

-- First let's make a query without OOPS substitution
select
    l_returnflag,
    l_linestatus,
    sum(l_quantity) as sum_qty,
    sum(l_extendedprice) as sum_base_price,
    sum(l_extendedprice*(1-l_discount)) as sum_disc_price,
    sum(l_extendedprice*(1-l_discount)*(1+l_tax)) as sum_charge,
    avg(l_quantity) as avg_qty,
    avg(l_extendedprice) as avg_price,
    avg(l_discount) as avg_disc,
    count(*) as count_order
from
    lineitem
where
    l_shipdate <= '1998-12-01'
group by
    l_returnflag,
    l_linestatus
order by
    l_returnflag,
    l_linestatus;
----

// Делаю прямо тут кастомный css для блоков вывода, чтобы просто показать идею разных литеральных блоков (для ввода и вывода)
++++
<style>
.output {
  background-color: lightgrey;
  font-family: "Noto Sans Mono", monospace;
}
</style>
++++

[output]
--
output from previous code block
--

[source,postgres]
----
-- Now let's make the same query but with OOPS substitution set to ON
set OOPS.auto_substitute_projections TO on;

select
    l_returnflag,
    l_linestatus,
    sum(l_quantity) as sum_qty,
    sum(l_extendedprice) as sum_base_price,
    sum(l_extendedprice*(1-l_discount)) as sum_disc_price,
    sum(l_extendedprice*(1-l_discount)*(1+l_tax)) as sum_charge,
    avg(l_quantity) as avg_qty,
    avg(l_extendedprice) as avg_price,
    avg(l_discount) as avg_disc,
    count(*) as count_order
from
    lineitem
where
    l_shipdate <= '1998-12-01'
group by
    l_returnflag,
    l_linestatus
order by
    l_returnflag,
    l_linestatus;
----

[output]
--
output from previous code block
--