= [.commercial]#OOPS# projections and automatic table substitution
Alexey Bogdanov
:keywords: OOPS, projection, vector
:lang: en
:description: This article describes the usage of OOPS projections
:version: 1
:source-highlighter: highlight.js
:highlightjs-theme: paraiso-light


// Краткое описание заворачиваем в тэг, чтобы его можно было использовать в других местах, 
// например в сниппетах в результатах поиска
// tag::short-description[]
// Здесь хорошо бы дать расшифровку аббревиатуры OOPS в скобках, но мне не удалось ее найти
The [.commercial]#OOPS# provides some functions simplifying creation and usage of projections.
// end::short-description[]

// Предположим, что описанный функционал появится начиная с версии 2
// В таком случае данный фрагмент показываем только, если версия меньше 2
ifeval::[{version} < 2]

In future it may be added to [.commercial]#SQL# grammar, so that it is possible to write:

endif::[]


// Вариант для версий начиная с 2
ifeval::[{version} >= 2]

To use OOPS you can run this code:

endif::[]


[source,sql]
----
CREATE PROJECTION xxx OF TABLE yyy(column1, column2, ...) GROUP BY (column1, column2, ...)
----

// Этот фрагмент тоже показываем только, если версия меньше 2
ifeval::[{version} < 2]

But right now it can be done using function:

include::docstrings/function_create_projection.adoc[]

The `<<create_projection:order_by>>` attribute is one of the OOPS projection vector columns by which data is sorted. 
Presence of such column in projection allows to incrementally update projection.
// Здесь нужны будут ссылки на описание (докстринги) этих методов
Generated `+PNAME_refresh()+` method calls `+populate()+` method, selecting from original table only rows with `+order_by+` column value greater than maximal value of this column
in projection.
It assumes that `+order_by+` is unique or at least refresh is done at the moment when there is some gap in collected events.

Like materialized views, [.commercial]#OOPS# projections are not updated automatically.
It is responsibility of a programmer to periodically refresh them.
The most convenient way is to use generated `+PNAME_refresh()+` function.
If `<<create_projection:order_by>>` attribute is specified, this function imports from original table only the new data (not present in projection).

endif::[]

The main advantage of [.commercial]#OOPS# projection mechanism is that it allows to automatically substitute queries on original tables with projections.
// Здесь нужна будет ссылка на описание параметра OOPS.auto_substitute_projections
There is `+OOPS.auto_substitute_projections+` configuration parameter which allows to switch on such substitution.
// Здесь я исправил projects на projections, но не уверен на 100%, что это правильно (не хватает данных)
By default it is switched off, because OOPS projections may be not synchronized with original table and query on projection may return different result.

// Этот фрагмент тоже показываем только, если версия меньше 2
ifeval::[{version} < 2]

Right now projections can be automatically substituted only if:

[arabic]
. Query doesn’t contain JOINs.
. Query performs aggregation of vector (tile) columns.
. All other expressions in target list, `+ORDER BY+` / `+GROUP BY+`
clauses refer only to scalar attributes of projection.

Example of using projections:

// В этом примере хорошо бы было показать результаты выполнения запросов
// Насколько я понимаю, должна быть какая-то разница во времени выполнения с OOPS и без
// В таком виде, как сейчас, пример не очень показателен
//[source,postgres]
[source,sql]
----
create extension OOPS;

-- Let's create a demo table
create table lineitem(
    l_orderkey integer,
    l_partkey integer,
    l_suppkey integer,
    l_linenumber integer,
    l_quantity real,
    l_extendedprice real,
    l_discount real,
    l_tax real,
    l_returnflag "char",
    l_linestatus "char",
    l_shipdate date,
    l_commitdate date,
    l_receiptdate date,
    l_shipinstruct char(25),
    l_shipmode char(10),
    l_comment char(44),
    l_dummy char(1));

select
create_projection(
    'OOPS_lineitem',
    'lineitem',
    array['l_shipdate','l_quantity','l_extendedprice','l_discount','l_tax'],
    array['l_returnflag','l_linestatus']);

-- Switching on timing to see the difference
\timing

-- Copying demo table
copy lineitem from '/mnt/data/lineitem.tbl' delimiter '|' csv;

-- Refreshing the projections
select OOPS_lineitem_refresh();

-- First let's make a query without OOPS substitution
select
    l_returnflag,
    l_linestatus,
    sum(l_quantity) as sum_qty,
    sum(l_extendedprice) as sum_base_price,
    sum(l_extendedprice*(1-l_discount)) as sum_disc_price,
    sum(l_extendedprice*(1-l_discount)*(1+l_tax)) as sum_charge,
    avg(l_quantity) as avg_qty,
    avg(l_extendedprice) as avg_price,
    avg(l_discount) as avg_disc,
    count(*) as count_order
from
    lineitem
where
    l_shipdate <= '1998-12-01'
group by
    l_returnflag,
    l_linestatus
order by
    l_returnflag,
    l_linestatus;
----

[output]
--
output from previous code block
--

//[source,postgres]
[source,sql]
----
-- Now let's make the same query but with OOPS substitution set to ON
set OOPS.auto_substitute_projections TO on;

select
    l_returnflag,
    l_linestatus,
    sum(l_quantity) as sum_qty,
    sum(l_extendedprice) as sum_base_price,
    sum(l_extendedprice*(1-l_discount)) as sum_disc_price,
    sum(l_extendedprice*(1-l_discount)*(1+l_tax)) as sum_charge,
    avg(l_quantity) as avg_qty,
    avg(l_extendedprice) as avg_price,
    avg(l_discount) as avg_disc,
    count(*) as count_order
from
    lineitem
where
    l_shipdate <= '1998-12-01'
group by
    l_returnflag,
    l_linestatus
order by
    l_returnflag,
    l_linestatus;
----

[output]
--
output from previous code block
--

endif::[]

// Делаю прямо тут кастомный css для блоков вывода, чтобы просто показать идею разных литеральных блоков (для ввода и вывода)
++++
<style>
.output {
  background-color: lightgrey;
  font-family: "Noto Sans Mono", monospace;
}
.commercial {
  font-weight: bold;
}
</style>
++++

